# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/cassette from release v0.1.0. Edit the generator, not this file.
class Cassette < Formula
  desc "Record/replay HTTP server for Dekopon provider baseUrl"
  homepage "https://github.com/dekopon-agents/cassette"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/cassette/releases/download/v0.1.0/cassette-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "b97f055f6557f76e1ffc848b5e9fd0d0742f7412e1b944cb1b70235d9e7f55b7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/cassette/releases/download/v0.1.0/cassette-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "328dd515f8a96f7c6ccc800f607b16cec562a79d4525d8c2968b4f59d470fa35"
    end

    on_intel do
      url "https://github.com/dekopon-agents/cassette/releases/download/v0.1.0/cassette-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "eb8fc0d97fda0fb8442b9016941023e835db384801960637dde1c0435c58da86"
    end
  end

  def install
    bin.install "cassette"
    doc.install "README.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  test do
    assert_match "cassette #{version}", shell_output("#{bin}/cassette --version")
  end
end
