# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/cm from release v0.1.2. Edit the generator, not this file.
class Cm < Formula
  desc "Campaign manager: the campaign lifecycle as one tool"
  homepage "https://github.com/dekopon-agents/cm"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.2/cm-0.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "d78af46ce434d668f0a3231c6c86433e239b3c85b1e6c5b3915753f531eff312"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.2/cm-0.1.2-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e67f38dc0e97e8cf3b6ab5f93d4297af1fbbdace205081af5e0f4a4e86c8e5ce"
    end

    on_intel do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.2/cm-0.1.2-x86_64-unknown-linux-musl.tar.gz"
      sha256 "81ffac703638307439edf0d3cbb445b7d11c8eea803e9acb1c865af157c96ca7"
    end
  end

  def install
    bin.install "cm"
    doc.install "README.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  test do
    assert_match "cm #{version}", shell_output("#{bin}/cm --version")
  end
end
