# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/cm from release v0.1.0. Edit the generator, not this file.
class Cm < Formula
  desc "Campaign manager: the campaign lifecycle as one tool"
  homepage "https://github.com/dekopon-agents/cm"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.0/cm-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "e989e7d84d0cd03c9cda971b125897e02a1b79f8e25c1ba4a8bc6c33a5508790"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.0/cm-0.1.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "a3c70e29207d8fa8c8e60ddc6d2cbaa0bd28b28cedd718302dfc63e58b446bb1"
    end

    on_intel do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.0/cm-0.1.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8e129f311ab870c53cd19d8a441823602d3f2352e8c80a4145232967a38298a2"
    end
  end

  def install
    bin.install "cm"
    doc.install "README.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  test do
    assert_match "cm #{version}", shell_output("#{bin}/cm --version")
  end
end
