# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/cm from release v0.1.1. Edit the generator, not this file.
class Cm < Formula
  desc "Campaign manager: the campaign lifecycle as one tool"
  homepage "https://github.com/dekopon-agents/cm"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.1/cm-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "ad10c05b901d0a09aa3d23f8d0b3b698cb638760f12f39390bb5b37a68c621d4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.1/cm-0.1.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "dba3ac3a3c70c60887ec97302f842211efb41e7ec51c2bbbcf3739ab42ea0887"
    end

    on_intel do
      url "https://github.com/dekopon-agents/cm/releases/download/v0.1.1/cm-0.1.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "e6d44d91201ba066b176d6fa6e98e35bca3b9f739efb8968dfca00a6a9e264b6"
    end
  end

  def install
    bin.install "cm"
    doc.install "README.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  test do
    assert_match "cm #{version}", shell_output("#{bin}/cm --version")
  end
end
