# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/dekopon-console from release v0.12.0. Edit the generator, not this file.
class DekoponConsole < Formula
  desc "Interactive terminal console for a running Dekopon broker"
  homepage "https://github.com/dekopon-agents/dekopon-console"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.12.0/dekopon-console-0.12.0-aarch64-apple-darwin.tar.gz"
      sha256 "c8bc2339011c957d67453f22fc29e423bfb1916375981e523128ef5b26cf227a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.12.0/dekopon-console-0.12.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4175e7d53eb470652afd9d9a64d2599e4acc455db1a41bdba81c16bbed593795"
    end

    on_intel do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.12.0/dekopon-console-0.12.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "bcbd451a3bc05b4b70156307a03340f03bbe3d74c65c0d773211b9a5e8a28667"
    end
  end

  def install
    bin.install "dekopon-console"
    doc.install "README.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  test do
    assert_match "dekopon-console #{version}", shell_output("#{bin}/dekopon-console --version")
  end
end
