# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/dekopon-console from release v0.5.0. Edit the generator, not this file.
class DekoponConsole < Formula
  desc "Interactive terminal console for a running Dekopon broker"
  homepage "https://github.com/dekopon-agents/dekopon-console"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.5.0/dekopon-console-0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "272ecc482c77b362ca58733110801855f06513dc21f6c1c155962d4abab1f9cc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.5.0/dekopon-console-0.5.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "38645ca152a3117da6b5a8cbc4e51deae5c40010554c88e8028b48af9c3d7142"
    end

    on_intel do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.5.0/dekopon-console-0.5.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2772724824e8f322dc23ca410d57afacc06f20a1febfc404f5ace9a37d801b2e"
    end
  end

  def install
    bin.install "dekopon-console"
    doc.install "README.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  test do
    assert_match "dekopon-console #{version}", shell_output("#{bin}/dekopon-console --version")
  end
end
