# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/dekopon-console from release v0.4.0. Edit the generator, not this file.
class DekoponConsole < Formula
  desc "Interactive terminal console for a running Dekopon broker"
  homepage "https://github.com/dekopon-agents/dekopon-console"
  license any_of: ["Apache-2.0", "MIT"]

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.4.0/dekopon-console-0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "d3323ed50410f1e3d08386b2ac18977df9ae492b12424d9cb9cf6b23c5962e0e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.4.0/dekopon-console-0.4.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "138100fef631e43640a93585a1e44e206c9008fd34b78d0ae61de0d7af262302"
    end

    on_intel do
      url "https://github.com/dekopon-agents/dekopon-console/releases/download/v0.4.0/dekopon-console-0.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2ed5462fc71400b646d42441da93b47392fd0f0fb6eacf276262ba1102ecac59"
    end
  end

  def install
    bin.install "dekopon-console"
    doc.install "README.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  test do
    assert_match "dekopon-console #{version}", shell_output("#{bin}/dekopon-console --version")
  end
end
