# Dekopon publishes one archive per platform carrying every executable, so
# one formula installs the whole system. Separate per-executable formulae would
# each download the same tarball.
#
# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/dekopon, from the archives release v0.33.0 published.
# Which platforms Dekopon supports is a property of each release, not of this
# tap. Edit the generator, not this file.
class Dekopon < Formula
  desc "Capability-oriented control plane for self-hosted AI agents"
  homepage "https://github.com/dekopon-agents/dekopon"
  license any_of: ["Apache-2.0", "MIT"]
  # No explicit `version`: Homebrew scans 0.33.0 out of the download URL, and
  # `brew audit --strict` rejects restating it.

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.33.0/dekopon-0.33.0-aarch64-apple-darwin.tar.gz"
      sha256 "fb87b31fd7a5a3590def23c6f4a05822fcb1ddc24bf1f206c299da0e812bc7ae"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.33.0/dekopon-0.33.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "82388d27cfd8ed3d7904167a80ee9073d3857e028725d17f54fad5a1a04a807b"
    end

    on_intel do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.33.0/dekopon-0.33.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8c158bcadb30b5782edd6197773787ccbefff9f09af2dfdb80e32c14dbf8ccd3"
    end
  end

  def install
    bin.install "dekopon-brokerd", "dekopond"
    doc.install "README.md", "BROKER.md", "GATEWAY.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  def caveats
    <<~EOS
      Dekopon installed two executables:

        dekopon-brokerd  the authorization broker daemon (Unix only)
        dekopond         the unprivileged chat gateway daemon (Unix only)

      Manage model authentication without starting a daemon:

        dekopond auth chatgpt --help

      Check a configuration offline, as startup would, before deploying it:

        dekopon-brokerd check broker.d --provider-set providers.yaml --store DIR
        dekopond check dekopond.d --catalog agents.d

      dekopon-brokerd and dekopond are daemons. Nothing was started, and neither
      runs until you write it an owner-authored configuration file:

        dekopon-brokerd --config broker.yaml    #{doc}/BROKER.md
        dekopond --config gateway.yaml          #{doc}/GATEWAY.md

      The broker holds provider credentials and the only authorization path;
      read BROKER.md before enabling it.

      The end-to-end walkthrough is examples/conditional-write in the source tree:
      https://github.com/dekopon-agents/dekopon/tree/v0.33.0/examples/conditional-write/README.md
    EOS
  end

  test do
    assert_match "dekopon-brokerd #{version}", shell_output("#{bin}/dekopon-brokerd --version")
    assert_match "dekopond #{version}", shell_output("#{bin}/dekopond --version")

    assert_match "--expose-credential",
                 shell_output("#{bin}/dekopond auth chatgpt export --help")
    assert_match '"signedIn": false',
                 shell_output("#{bin}/dekopond auth chatgpt status --auth-file #{testpath}/missing-auth.json -o json")
  end
end
