# Dekopon publishes one archive per platform carrying every executable, so
# one formula installs the whole system. Separate per-executable formulae would
# each download the same tarball.
#
# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/dekopon, from the archives release v0.15.0 published.
# Which platforms Dekopon supports is a property of each release, not of this
# tap. Edit the generator, not this file.
class Dekopon < Formula
  desc "Capability-oriented control plane for self-hosted AI agents"
  homepage "https://github.com/dekopon-agents/dekopon"
  license any_of: ["Apache-2.0", "MIT"]
  # No explicit `version`: Homebrew scans 0.15.0 out of the download URL, and
  # `brew audit --strict` rejects restating it.

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.15.0/dekopon-0.15.0-aarch64-apple-darwin.tar.gz"
      sha256 "75b873fecbc10183c7e4c2d84ca5593cda046205489b3197143753a36f7096f2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.15.0/dekopon-0.15.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "162dadb98e35b836e7a531097367d019650ed5efb869cfc508bac8f0bb7fe8ba"
    end

    on_intel do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.15.0/dekopon-0.15.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "a623c7abc0833d6ce4887c8a4f3f36ffc9db822bf20f1d977eea88a7c7d307d3"
    end
  end

  def install
    bin.install "dekopon-brokerd", "dekopond"
    pkgshare.install "providers"
    doc.install "README.md", "BROKER.md", "GATEWAY.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  def caveats
    <<~EOS
      Dekopon installed two executables:

        dekopon-brokerd  the authorization broker daemon (Unix only)
        dekopond         the unprivileged chat gateway daemon (Unix only)

      Manage model authentication without starting a daemon:

        dekopond auth chatgpt --help

      dekopon-brokerd and dekopond are daemons. Nothing was started, and neither
      runs until you write it an owner-authored configuration file:

        dekopon-brokerd --config broker.yaml    #{doc}/BROKER.md
        dekopond --config gateway.yaml          #{doc}/GATEWAY.md

      The broker holds provider credentials and the only authorization path;
      read BROKER.md before enabling it.

      The example JSONPlaceholder provider component is at

        #{pkgshare}/providers/jsonplaceholder-provider.wasm

      It imports broker-owned HTTP, which makes it a broker provider:
      name its path in broker.yaml. The constraint set and Cedar policy it needs are
      in #{pkgshare}/providers/JSONPLACEHOLDER.md.

      The end-to-end walkthrough is examples/conditional-write in the source tree:
      https://github.com/dekopon-agents/dekopon/tree/v0.15.0/examples/conditional-write/README.md
    EOS
  end

  test do
    assert_match "dekopon-brokerd #{version}", shell_output("#{bin}/dekopon-brokerd --version")
    assert_match "dekopond #{version}", shell_output("#{bin}/dekopond --version")

    component = pkgshare/"providers/jsonplaceholder-provider.wasm"
    assert_path_exists component
    assert_equal "\x00asm", component.binread(4), "example provider is not a Wasm component"

    assert_match "--expose-credential",
                 shell_output("#{bin}/dekopond auth chatgpt export --help")
    assert_match '"signedIn": false',
                 shell_output("#{bin}/dekopond auth chatgpt status --auth-file #{testpath}/missing-auth.json -o json")
  end
end
