# Dekopon publishes one archive per platform carrying every executable, so
# one formula installs the whole system. Separate per-executable formulae would
# each download the same tarball.
#
# Generated by .github/scripts/render-homebrew-formula.py in
# https://github.com/dekopon-agents/dekopon, from the archives release v0.32.0 published.
# Which platforms Dekopon supports is a property of each release, not of this
# tap. Edit the generator, not this file.
class Dekopon < Formula
  desc "Capability-oriented control plane for self-hosted AI agents"
  homepage "https://github.com/dekopon-agents/dekopon"
  license any_of: ["Apache-2.0", "MIT"]
  # No explicit `version`: Homebrew scans 0.32.0 out of the download URL, and
  # `brew audit --strict` rejects restating it.

  on_macos do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.32.0/dekopon-0.32.0-aarch64-apple-darwin.tar.gz"
      sha256 "001e5c995a2dabd039f048f297feb27a5f2081d56cc557b9429288b5c36d92d4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.32.0/dekopon-0.32.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8791d7879001e5b80b9225635af9c0ad14b71ebd96193b539c6b3d7abb16f017"
    end

    on_intel do
      url "https://github.com/dekopon-agents/dekopon/releases/download/v0.32.0/dekopon-0.32.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1b1c1b06a009205d2a1f1c88fac3c84f75e434b2ee1d2746152be0430d4d6636"
    end
  end

  def install
    bin.install "dekopon-brokerd", "dekopond"
    doc.install "README.md", "BROKER.md", "GATEWAY.md", "LICENSE-APACHE", "LICENSE-MIT"
  end

  def caveats
    <<~EOS
      Dekopon installed two executables:

        dekopon-brokerd  the authorization broker daemon (Unix only)
        dekopond         the unprivileged chat gateway daemon (Unix only)

      Manage model authentication without starting a daemon:

        dekopond auth chatgpt --help

      Check a configuration offline, as startup would, before deploying it:

        dekopon-brokerd check broker.d --provider-set providers.yaml --store DIR
        dekopond check dekopond.d --catalog agents.d

      dekopon-brokerd and dekopond are daemons. Nothing was started, and neither
      runs until you write it an owner-authored configuration file:

        dekopon-brokerd --config broker.yaml    #{doc}/BROKER.md
        dekopond --config gateway.yaml          #{doc}/GATEWAY.md

      The broker holds provider credentials and the only authorization path;
      read BROKER.md before enabling it.

      The end-to-end walkthrough is examples/conditional-write in the source tree:
      https://github.com/dekopon-agents/dekopon/tree/v0.32.0/examples/conditional-write/README.md
    EOS
  end

  test do
    assert_match "dekopon-brokerd #{version}", shell_output("#{bin}/dekopon-brokerd --version")
    assert_match "dekopond #{version}", shell_output("#{bin}/dekopond --version")

    assert_match "--expose-credential",
                 shell_output("#{bin}/dekopond auth chatgpt export --help")
    assert_match '"signedIn": false',
                 shell_output("#{bin}/dekopond auth chatgpt status --auth-file #{testpath}/missing-auth.json -o json")
  end
end
